ignorePatterns:
  - node_modules/**
  - dist/**
  - build/**

overrides:
  - files:
      - "**/*.{js,jsx,mjs,cjs}"

    env:
      browser: true

    parserOptions:
      ecmaVersion: latest
      sourceType: module
      ecmaFeatures:
        jsx: true

    plugins:
      - react
      - prettier

    extends:
      - eslint:recommended
      - plugin:react/recommended
      - prettier
    rules:

      prettier/prettier: error

      react/react-in-jsx-scope: off
      react/prop-types: off

    settings:
      react:
        version: detect
        runtime: automatic
