# Игнорируем артефакты сборки и node_modules
ignorePatterns:
  - node_modules/**
  - dist/**
  - build/**

# Применяем конфигурацию ко всем JS(+JSX/MJS/CJS)
overrides:
  - files:
      - "**/*.{js,jsx,mjs,cjs}"
    # Указываем, что устанавливаем браузерные глобалы
    env:
      browser: true
    # Настройки парсера
    parserOptions:
      ecmaVersion: latest
      sourceType: module
      ecmaFeatures:
        jsx: true

    plugins:
      - react
      - prettier
    # Наследуем все рекомендации ESLint, React и Prettier
    extends:
      - eslint:recommended
      - plugin:react/recommended
      - prettier
    rules:
      # Ошибки Prettier
      prettier/prettier: error

      # Наши отключения React-правил
      react/react-in-jsx-scope: off
      react/prop-types: off

    settings:
      react:
        version: detect
        runtime: automatic
