name: Build Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4



      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install make
        run: sudo apt-get install -y make

      - name: Run make install
        run: make install

      - name: Run make build
        run: make build

        name: test
      - uses: qltysh/qlty-action/coverage@main
        with:
          coverage-token: {{secrets.qltcp_20nruZdbzSzLu0eN}}
          files: target/lcov.info